In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Import required packages

import numpy as np
import pandas as pd
import mlba
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, confusion_matrix 
from imblearn.over_sampling import SMOTENC
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

## Modeling (Name)

Predicting Credit Card Defaults

Mia Arnold - Katia Paredes - Harshali Gaikwad

Shirley Marcos School of Engineering, University of San Diego

ADS-505 Applied Data Science for Buisness

October 19th, 2026

## Table of Contents
1. [Data Preprocessing](#Data-Preprocessing)
2. [Modeling with Demographic Info](#Modeling-with-Demographic-Info)
3. [Modeling without Demographic Info](#Modeling-without-Demographic-Info)
4. [Model Performance](#Model-Performance)
5. [Model Selection](#Model-Selection)
6. [Discussion](#Discussion)

# Data Preprocessing

In [3]:
# load data

df_1 = pd.read_csv("C:/Users/princ/OneDrive/Desktop/GitHub/ads505-final-project/data/credit_default_engineered.csv")
df_2 = df_1.drop(columns=['SEX','MARRIAGE','AGE'])

print(f'Shape of Data: {df_1.shape}')
print(f'Shape of Data w/o Demographics: {df_2.shape}')

Shape of Data: (30000, 40)
Shape of Data w/o Demographics: (30000, 37)

In [4]:
# test train split

train_1, holdout_1 = train_test_split(df_1, test_size=0.4, stratify=df_1['DEFAULT'], random_state=42)
holdout_1, validate_1 = train_test_split(holdout_1, test_size=0.5, stratify=holdout_1['DEFAULT'], random_state=42)
train_2, holdout_2 = train_test_split(df_2, test_size=0.4, stratify=df_2['DEFAULT'], random_state=42)
holdout_2, validate_2 = train_test_split(holdout_2, test_size=0.5, stratify=holdout_2['DEFAULT'], random_state=42)


# separate predictors and outcome

train_1_X = train_1.drop(columns=['DEFAULT_label','DEFAULT'])
train_1_y = train_1['DEFAULT']
holdout_1_X = holdout_1.drop(columns=['DEFAULT_label','DEFAULT'])
holdout_1_y = holdout_1['DEFAULT']
validate_1_X = validate_1.drop(columns=['DEFAULT_label','DEFAULT'])
validate_1_y = validate_1['DEFAULT']

train_2_X = train_2.drop(columns=['DEFAULT_label','DEFAULT'])
train_2_y = train_2['DEFAULT']
holdout_2_X = holdout_2.drop(columns=['DEFAULT_label','DEFAULT'])
holdout_2_y = holdout_2['DEFAULT']
validate_2_X = validate_2.drop(columns=['DEFAULT_label','DEFAULT'])
validate_2_y = validate_2['DEFAULT']

print(f'Shape of training data w/ Demo: {train_1_X.shape[0]}')
print(f'Shape of testing data w/ Demo: {holdout_1_X.shape[0]}')
print(f'Shape of validating data w/ Demo: {validate_1_X.shape[0]}')

print(f'Shape of training data w/o Demo: {train_2_X.shape[0]}')
print(f'Shape of testing data w/o Demo: {holdout_2_X.shape[0]}')
print(f'Shape of validating data w/o Demo: {validate_2_X.shape[0]}')

Shape of training data w/ Demo: 18000
Shape of testing data w/ Demo: 6000
Shape of validating data w/ Demo: 6000
Shape of training data w/o Demo: 18000
Shape of testing data w/o Demo: 6000
Shape of validating data w/o Demo: 6000

In [5]:
# SMOTE oversampling to address class imbalance

cat_cols = df_1.select_dtypes(include=['object', 'category', 'string']).columns.drop(['DEFAULT_label','Default'], errors='ignore').tolist()

cat_indices_1 = [train_1_X.columns.get_loc(col) for col in cat_cols]
cat_indices_2 = [train_2_X.columns.get_loc(col) for col in cat_cols]

print(f'Data Before Oversampling: {train_1_y.shape[0]}')
print(f'Data w/o Demo Info Before Oversampling: {train_2_y.shape[0]}')

smote_1 = SMOTENC(categorical_features=cat_indices_1, sampling_strategy='minority', random_state=42)

train_1_X, train_1_y = smote_1.fit_resample(train_1_X, train_1_y)

smote_2 = SMOTENC(categorical_features=cat_indices_2, sampling_strategy='minority', random_state=42)

train_2_X, train_2_y = smote_2.fit_resample(train_2_X, train_2_y)

print(f'Data After Oversampling: {train_1_y.shape[0]}')
print(f'Data w/o Demo Info After Oversampling: {train_2_y.shape[0]}')

Data Before Oversampling: 18000
Data w/o Demo Info Before Oversampling: 18000
Data After Oversampling: 28036
Data w/o Demo Info After Oversampling: 28036

In [6]:
# create dummy variables for categorical data

train_1_X_encoded = pd.get_dummies(train_1_X)
holdout_1_X_encoded = pd.get_dummies(holdout_1_X)
holdout_1_X_encoded = holdout_1_X_encoded.reindex(columns=train_1_X_encoded.columns, fill_value=0)

train_2_X_encoded = pd.get_dummies(train_2_X)
holdout_2_X_encoded = pd.get_dummies(holdout_2_X)
holdout_2_X_encoded = holdout_2_X_encoded.reindex(columns=train_2_X_encoded.columns, fill_value=0)

In [7]:
# normalize

scaler = StandardScaler()

train_1_X_norm = scaler.fit_transform(train_1_X_encoded)
holdout_1_X_norm = scaler.transform(holdout_1_X_encoded)

train_2_X_norm = scaler.fit_transform(train_2_X_encoded)
holdout_2_X_norm = scaler.transform(holdout_2_X_encoded)

# Modeling with Demographic Info

In [8]:
# Baseline model

baseline = DummyClassifier(strategy="constant", constant=0)

baseline.fit(train_1_X, train_1_y)

base_1_pred = baseline.predict(holdout_1_X)

mlba.classificationSummary(y_true=holdout_1_y, y_pred=base_1_pred)

Confusion Matrix (Accuracy 0.7788)

       Prediction
Actual    0    1
     0 4673    0
     1 1327    0

In [9]:
# Adaboost

In [10]:
# Linear Discriminant Analysis (LDA)

In [11]:
# Random Forest

In [12]:
# Logistic Regression

In [13]:
# Neural Network

In [14]:
# Decision Tree

# Modeling without Demographic Info

In [15]:
# Baseline model

baseline = DummyClassifier(strategy="constant", constant=0)

baseline.fit(train_2_X, train_2_y)

base_2_pred = baseline.predict(holdout_2_X)

mlba.classificationSummary(y_true=holdout_2_y, y_pred=base_2_pred)

Confusion Matrix (Accuracy 0.7788)

       Prediction
Actual    0    1
     0 4673    0
     1 1327    0

In [16]:
# Adaboost

In [17]:
# Linear Discriminant Analysis (LDA)

In [18]:
# Random Forest

In [19]:
# Logistic Regression

In [20]:
# Neural Network

In [21]:
# Decision Tree

# Model Performance

In [22]:
# Baseline w/ Demo

acc = accuracy_score(holdout_1_y, base_1_pred)
prec = precision_score(holdout_1_y, base_1_pred)
rec = recall_score(holdout_1_y, base_1_pred)

tn, fp, fn, tp = confusion_matrix(holdout_1_y, base_1_pred).ravel()

fpr = fp / (fp + tn)

F1 = 2*tp/(2*tp + fp + fn)

eval_metrics = [["Accuracy", acc],["Precision", prec],["Recall", rec],["FPR", fpr],["F1 Score", F1]]
eval_metrics_ada_1=pd.DataFrame(eval_metrics, columns=["Metric", "Value"])
eval_metrics_ada_1

      Metric     Value
0   Accuracy  0.778833
1  Precision  0.000000
2     Recall  0.000000
3        FPR  0.000000
4   F1 Score  0.000000

In [23]:
# Adaboost w/ Demo

In [24]:
# Linear Discriminant Analysis (LDA) w/ Demo

In [25]:
# Random Forest w/ Demo

In [26]:
# Logistic Regression w/ Demo

In [27]:
# Neural Network w/ Demo

In [28]:
# Decision Tree w/ Demo

In [29]:
# Baseline w/o Demo

acc = accuracy_score(holdout_2_y, base_2_pred)
prec = precision_score(holdout_2_y, base_2_pred)
rec = recall_score(holdout_2_y, base_2_pred)

tn, fp, fn, tp = confusion_matrix(holdout_2_y, base_2_pred).ravel()

fpr = fp / (fp + tn)

F1 = 2*tp/(2*tp + fp + fn)

eval_metrics = [["Accuracy", acc],["Precision", prec],["Recall", rec],["FPR", fpr],["F1 Score", F1]]
eval_metrics_ada_1=pd.DataFrame(eval_metrics, columns=["Metric", "Value"])
eval_metrics_ada_1

      Metric     Value
0   Accuracy  0.778833
1  Precision  0.000000
2     Recall  0.000000
3        FPR  0.000000
4   F1 Score  0.000000

In [30]:
# Adaboost w/o Demo

In [31]:
# Linear Discriminant Analysis (LDA) w/o Demo

In [32]:
# Random Forest w/o Demo

In [33]:
# Logistic Regression w/o Demo

In [34]:
# Neural Network w/o Demo

In [35]:
# Decision Tree w/o Demo

# Model Selection

# Discussion